# app/models/user.py

from typing import Optional
from datetime import datetime, timezone
from sqlmodel import Field, SQLModel


# ─── User Model ───────────────────────────────────────────────────────────────
class User(SQLModel, table=True):
    """
    This class represents the 'user' table in PostgreSQL.

    Every attribute here becomes a column in the table.
    SQLModel reads this class and creates the table automatically
    when we call create_db_and_tables() in main.py

    Table structure in PostgreSQL:
        users
        ├── id          (integer, primary key, auto increment)
        ├── email       (string, unique, not null)
        ├── full_name   (string, not null)
        ├── password    (string, not null) ← stores hashed password
        ├── is_active   (boolean, default true)
        └── created_at  (datetime, auto set on creation)
    """

    id: Optional[int] = Field(default=None, primary_key=True, description="Unique identifier for each user, auto generated by database")
    email: str = Field(unique=True, index=True, description="User email address — must be unique")
    username: str = Field(description="User's display name")
    hashed_password: str = Field(description="Bcrypt hashed password — never plain text")
    is_active: bool = Field(default=True, description="Whether user account is active or deactivated")
    created_at: datetime = Field(default_factory=datetime.now(timezone.utc), description="Timestamp when user registered"
    )